### PR TITLE
Composer package updates for php8

### PR DESCRIPTION
**Pull request by marcguyer**

### CODE REVIEW

**Comment by Ocramius** [comment]
Could we add a `composer.lock`, to avoid issues with psalm/phpcs upgrades?

**Comment by marcguyer** [comment]
We now have composer lock file and mutually compatible `psr/log` version. I'm entirely new to psalm so I could use some help with these errors.

**Comment by Ocramius** [comment]
I think all `getMockBuilder()` errors are fixed by using `getMock()` directly 👍

**Comment by marcguyer** [comment]
Assuming you mean, e.g., changing ...

```php
$session = $this->getMockBuilder(SessionInterface::class)->getMock();
```
... to this ... 
```php
$session = $this->createMock(SessionInterface::class);
```
... should fix this error ...  
> Error: Method PSR7Sessions\Storageless\Session\SessionInterface::expects does not exist

I tried that but found no change to Psalm errors. Psalm is complaining as if `$session` is a concrete implementation of SessionInterface rather than an instance of MockObject. Right?

**Comment by Ocramius** [comment]
@marcguyer I've pushed e92579a to your fork, which contains the fixes needed to get psalm happy :-)

**Review by Ocramius — APPROVED** [review]
Thanks @marcguyer! :ship:

**Pull request merged**
