### PR TITLE
added `~8.1.0` php version to composer.json

### PR DESCRIPTION
**Pull request by tempfirstuser**

### CODE REVIEW

**Comment by tempfirstuser** [comment]
@Ocramius this PR should close issue #39

**Comment by Ocramius** [comment]
Seems like PHPUnit.xml.dist requires adjusting to the 9.5+ format

**Comment by tempfirstuser** [comment]
@Ocramius @marcguyer I've found somewhere this information from the page with this title "Upgrade PHPUnit to 9.5.x" 

> The old "<filter/whitelist>" section has been renamed to "<coverage/include>", and "<exclude>" is now a child of "<coverage>", not of "<include>". In parallel, the "whitelistfolders" and "whitelistfiles" used in our "coverage.php" files have been deprecated and replaced by "includelistfolders" and "includelistfiles". Old ones will continue working but a warning will be shown when creating the test site.

But I need to check this yet.

**Review by Ocramius — APPROVED** [review]
LGTM, thanks @tempfirstuser, @marcguyer!

**Pull request merged**
